title: "MTH113 Notes"  # 站点标题
description: "Notes for the MTH113 course"  # 站点描述
url: "https://HZzzzz411.github.io/MTH113-Notes"  # 站点的 URL
baseurl: ""  # 因为您的仓库是顶层仓库，所以 baseurl 为空

# 指定源分支
source: "main"

# 指定 Jekyll 应该生成哪些文件和目录
collections:
  main:
    output: true  # 指定集合是否应该被输出为静态文件

exclude:
  - vendor/
  - script/
  - Gemfile.lock
  - node_modules/
  - package.json
  - package-lock.json

# 插件
plugins:
  - jekyll-seo-tag  # 用于 SEO 优化
  - jekyll-sitemap  # 自动生成站点地图

# 集合配置
collections:
  main:
    output: true  # 确保集合中的文档被输出为静态页面

# 永久链接（URLs）设置
permalink: pretty  # 设置文章的 URL 格式为 /:categories/:year/:month/:day/:title/

# 其他配置
defaults:
  - scope:
      path: ""  # 应用于所有文件
      type: "posts"  # 如果有文章的话
    values:
      layout: "default"  # 默认布局
  - scope:
      path: ""  # 应用于所有文件
      type: "main"  # 应用于集合 'main'
    values:
      layout: "default"  # 默认布局
